name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'maven'
      
      - name: Set up Maven
        uses: mvn/setup-maven@v1
        with:
          maven-version: '3.8.1'

      - name: Build and package
        run: |
          mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zoo.jar
          path: target/zoo-1.0-SNAPSHOT.jar
