name: Print Current Date

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  print-date:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date
        run: |
          date
